name: Snyk Security Scan â€” Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  snyk-sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 with Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Verify Maven
        run: mvn -version

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk #d
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Run Snyk test but DO NOT stop workflow if it fails
      - name: Snyk Test for Maven (Quality Gate)
        working-directory: JtProject
        continue-on-error: true
        run: snyk test --maven-executable=mvn --severity-threshold=medium

      # Always upload results to Snyk portal even if the test step fails
      - name: Snyk Monitor (Always Upload Results)
        if: always()
        working-directory: JtProject
        run: snyk monitor --maven-executable=mvn
